//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows;
using System.Windows.Media;
using System.Windows.Media.Effects;
using System.Windows.Media.Media3D;


namespace VrPlayer.Models.Effects
{	
	public class UnwrapFishEyeStereoEffect : ShaderEffect {
		public static readonly DependencyProperty InputProperty = ShaderEffect.RegisterPixelShaderSamplerProperty("Input", typeof(UnwrapFishEyeStereoEffect), 0);
		public static readonly DependencyProperty SampleInputParamProperty = DependencyProperty.Register("SampleInputParam", typeof(double), typeof(UnwrapFishEyeStereoEffect), new UIPropertyMetadata(((double)(3.5D)), PixelShaderConstantCallback(0)));
		public UnwrapFishEyeStereoEffect() {
			PixelShader pixelShader = new PixelShader();
            pixelShader.UriSource = new Uri("pack://application:,,,/Models/Effects/UnwrapFishEyeStereoEffect.ps");
			this.PixelShader = pixelShader;

			this.UpdateShaderValue(InputProperty);
			this.UpdateShaderValue(SampleInputParamProperty);
		}
		public Brush Input {
			get {
				return ((Brush)(this.GetValue(InputProperty)));
			}
			set {
				this.SetValue(InputProperty, value);
			}
		}
		public double SampleInputParam {
			get {
				return ((double)(this.GetValue(SampleInputParamProperty)));
			}
			set {
				this.SetValue(SampleInputParamProperty, value);
			}
		}
	}
}
